"""``build_splits`` stage: corpus table → ``processed/splits.parquet``.

Runs as a versioned pipeline stage like every other derived artifact, so a
split can be regenerated byte-identically rather than being a script someone
ran once and cannot reproduce. That matters more here than elsewhere: once
models are trained and numbers published, nobody re-does the splits, so the
only defence against a quietly wrong split is being able to rebuild and
inspect it.

Only documents with real text are split. The 6,731 whitespace-only documents
(`empty_edited_text`) carry no supervision and would inflate every count.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

from oikonomia.config import Settings
from oikonomia.corpus.io import corpus_path, iter_batches
from oikonomia.logging import get_logger
from oikonomia.pipeline.manifest import upstream_key
from oikonomia.pipeline.stage import StageContext
from oikonomia.splits.assign import (
    DocRecord,
    assign_chronological,
    assign_random,
    build_groups,
    parse_genres,
    report_split,
)
from oikonomia.splits.dedup import cluster_duplicates

logger = get_logger(__name__)

SPLIT_COLUMNS = (
    "stem",
    "tm_id",
    "edited_text",
    "canonical_genres",
    "date_lo",
    "date_hi",
    "parse_flags",
)
OUTPUT_NAME = "splits.parquet"
REPORT_NAME = "splits_report.json"


def _load_records(settings: Settings) -> tuple[list[DocRecord], list[str]]:
    """Read the corpus table into split records, dropping textless documents."""
    records: list[DocRecord] = []
    texts: list[str] = []
    for df in iter_batches(corpus_path(settings.paths.processed), SPLIT_COLUMNS):
        for row in df.itertuples(index=False):
            if not str(row.edited_text).strip():
                continue
            lo, hi = row.date_lo, row.date_hi
            mid = None
            if pd.notna(lo) and pd.notna(hi):
                mid = (float(lo) + float(hi)) / 2
            elif pd.notna(lo):
                mid = float(lo)
            elif pd.notna(hi):
                mid = float(hi)
            records.append(
                DocRecord(
                    doc_id=str(row.stem),
                    tm_id=int(row.tm_id),
                    genre=parse_genres(row.canonical_genres),
                    date_mid=mid,
                )
            )
            texts.append(str(row.edited_text))
    return records, texts


class BuildSplitsStage:
    """Deterministic train/dev/test assignment under two regimes."""

    name = "build_splits"
    # 3: report residual temporal overlap in the chronological regime.
    # 2: stratify within each stratum, not against a global deficit (v1 put
    #    whole strata in train and only divided the ones processed last).
    version = "3"

    def inputs_key(self, s: Settings) -> str:
        # Splits derive entirely from the corpus table, so the fingerprint is
        # that table's identity — NOT the corpus rev. Keying on the rev misses
        # a rebuild of corpus.parquet from unchanged raw files (a parser fix),
        # which is exactly what happened with `<lb break="no"/>`.
        return upstream_key(s.paths.manifests, "build_corpus")

    def outputs(self, s: Settings) -> list[Path]:
        return [s.paths.processed / OUTPUT_NAME, s.paths.processed / REPORT_NAME]

    def params(self, s: Settings) -> dict[str, Any]:
        cfg = s.splits
        return {
            "seed": cfg.seed,
            "dup_threshold": cfg.dup_threshold,
            "train": cfg.train,
            "dev": cfg.dev,
            "test": cfg.test,
        }

    def run(self, ctx: StageContext) -> dict[str, float | int | str]:
        settings = ctx.settings
        settings.paths.ensure_writable()
        cfg = settings.splits
        fractions = {"train": cfg.train, "dev": cfg.dev, "test": cfg.test}

        records, texts = _load_records(settings)
        logger.info(f"build_splits: {len(records)} documents with text")

        dedup = cluster_duplicates(
            [r.doc_id for r in records],
            texts,
            threshold=cfg.dup_threshold,
            seed=cfg.seed,
        )
        logger.info(
            f"build_splits: {len(dedup.clusters)} duplicate clusters covering "
            f"{dedup.n_duplicated_docs} docs ({dedup.duplication_rate:.2%})"
        )

        groups = build_groups(records, dedup.cluster_of)
        for r in records:
            r.group_id = groups[r.doc_id]

        random_split = assign_random(records, fractions, seed=cfg.seed)
        chrono_split = assign_chronological(records, fractions)

        random_report = report_split(records, random_split, regime="random", seed=cfg.seed)
        chrono_report = report_split(
            records, chrono_split, regime="chronological", seed=cfg.seed
        )
        for rep in (random_report, chrono_report):
            if not rep.ok:
                msg = (
                    f"{rep.regime} split leaks {len(rep.leaked_groups)} group(s) "
                    "across splits; this is a bug, not a tuning problem"
                )
                raise ValueError(msg)

        table = pd.DataFrame(
            {
                "doc_id": [r.doc_id for r in records],
                "tm_id": [r.tm_id for r in records],
                "group_id": [r.group_id for r in records],
                "genre": [r.genre for r in records],
                "date_mid": [r.date_mid for r in records],
                "date_bucket": [r.date_bucket for r in records],
                "stratum": [r.stratum for r in records],
                "dup_cluster": [dedup.cluster_of[r.doc_id] for r in records],
                "split_random": [random_split[r.doc_id] for r in records],
                "split_chronological": [chrono_split[r.doc_id] for r in records],
            }
        )
        out = settings.paths.processed / OUTPUT_NAME
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp = out.with_suffix(".parquet.tmp")
        table.to_parquet(tmp, index=False)
        tmp.replace(out)

        report = {
            "n_docs": len(records),
            "dedup": {
                "n_clusters": len(dedup.clusters),
                "n_duplicated_docs": dedup.n_duplicated_docs,
                "duplication_rate": dedup.duplication_rate,
                "threshold": cfg.dup_threshold,
                "largest_clusters": [c.model_dump() for c in dedup.clusters[:10]],
            },
            "random": random_report.model_dump(),
            "chronological": chrono_report.model_dump(),
        }
        (settings.paths.processed / REPORT_NAME).write_text(
            json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        return {
            "n_docs": len(records),
            "n_groups": random_report.n_groups,
            "duplication_rate": dedup.duplication_rate,
            "max_stratum_drift": random_report.max_stratum_drift,
            "stratum_tv_train": random_report.stratum_tv_distance.get("train", 0.0),
            "temporal_overlap_rate": chrono_report.temporal_overlap_rate,
        }
