"""Build annotated.jsonl for the first 15 batch documents.

Spans are given as *surface strings in document order*, never as offsets: the
builder locates each one by scanning forward from the end of the previous span,
so an off-by-one is structurally impossible. Where a surface is ambiguous (a
bare "κ" that is a day number), a longer context string disambiguates it.
"""

import json
from pathlib import Path

# (label, surface, context|None, key|None) — document order, no overlaps.
E = lambda label, surface, ctx=None, key=None: (label, surface, ctx, key)  # noqa: E731

SPEC: dict[str, dict] = {}

SPEC["110220"] = {"entities": [
    E("PLACE", "Ῥώμης"),
    E("COMMODITY", "χλαμύδες χρωμάτιναι", None, "c1"),
    E("QUANTITY", "γ", "χρωμάτιναι γ", "q1"),
    E("COMMODITY", "μικρότερα", None, "c2"),
    E("QUANTITY", "α", "μικρότερα α", "q2"),
    E("COMMODITY", "λευκὰ", "λευκὰ α", "c3"),
    E("QUANTITY", "α", "λευκὰ α", "q3"),
    E("COMMODITY", "κολόβια λευκὰ", None, "c4"),
    E("QUANTITY", "β", "κολόβια λευκὰ β", "q4"),
    E("PLACE", "Ἀλεξάνδρειαν"),
    E("QUANTITY", "β", "τὰ πεμφθέντα β"),
    E("PERSON", "Ἀνεσίου"),
    E("COMMODITY", "κολόβια λευκὰ", None, "c5"),
    E("QUANTITY", "δ", "κολόβια λευκὰ δ", "q5"),
    E("COMMODITY", "ἀρρενικὰ", None, "c6"),
    E("QUANTITY", "α", "ἀρρενικὰ α", "q6"),
    E("PERSON", "Αἰλουρίωνος"),
    E("COMMODITY", "φαινόλης καλλάινος", None, "c7"),
    E("QUANTITY", "α", "καλλάινος α", "q7"),
    E("COMMODITY", "κολόβια λευκὰ Λαδικηνὰ", None, "c8"),
    E("QUANTITY", "α", "Λαδικηνὰ α", "q8"),
], "relations": [(f"c{i}", f"q{i}", "HAS_QUANTITY") for i in range(1, 9)]}

SPEC["11295"] = {"entities": [
    E("DATE_REF", "ὑπατείας", None, "date"),
    E("PERSON", "Μαξιμίνου"),
    E("PERSON", "Αὐρηλίων Γούνθου", None, "p_gounthos"),
    E("PERSON", "Αταρι", "καὶ Αταρι χωρὶς", "p_atari"),
    E("PERSON_ROLE", "χωρὶς κυρίου", None, "r_nokyrios"),
    E("PERSON", "Ατρεας", None, "p_atreas"),
    E("PERSON_ROLE", "μετὰ κυρίου"),
    E("PERSON", "Αὐρηλίου\nΝεμεσίωνος Ἰουλίου"),
    E("PERSON", "Θεοδώρας"),
    E("PERSON", "Ταύητος"),
    E("PERSON", "Σαμβαθοῦτος"),
    E("PERSON_ROLE", "ἀφηλίκων"),
    E("PERSON_ROLE", "μετὰ κυρίου"),
    E("PERSON", "Αὐρηλίου Γούνθου"),
    E("PERSON", "Παπνουθίου"),
    E("PERSON", "Τανίλλας"),
    E("PLACE", "κώμης Α…τ…"),
    E("PLACE", "Ἡρακλείδου μερίδος"),
    E("PLACE", "κώμῃ Φιλαδελφίᾳ"),
    E("COMMODITY", "οἰκίδιον μικρὸν μονόστεγον καὶ αὐλὴν", None, "house"),
    E("TRANSACTION", "ἐξοικονομοῦντες", None, "t1"),
    E("PERSON", "Αὐρηλίᾳ Ταπαϊτι", None, "p_buyer"),
    E("PERSON", "Πατερμουθίου"),
    E("PERSON", "Ταεισᾶτος"),
    E("PLACE", "κώμης Φιλαδελφίας"),
    E("PRICE_TERM", "τιμῆς"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "ταλάντου", None, "tal"),
    E("MONEY_AMOUNT", "ἑνὸς", None, "m1"),
    E("CURRENCY", "δραχμῶν", None, "dr"),
    E("MONEY_AMOUNT", "ἐνακοσίων", None, "m2"),
    E("PERSON", "Αὐρήλιοι Γοῦνθος"),
    E("PERSON", "Αταρις"),
    E("PERSON", "Ατρεα", "καὶ Ατρεα\n"),
    E("PERSON", "Ταύης"),
    E("PERSON", "Σαμβαθοῦς"),
    E("PERSON", "Αὐρηλίᾳ Ταπαϊτι"),
    E("COMMODITY", "οἰκίδιον καὶ αὐλὴν"),
], "relations": [
    ("m1", "tal", "HAS_CURRENCY"), ("m2", "dr", "HAS_CURRENCY"),
    ("house", "m1", "HAS_PRICE"), ("house", "m2", "HAS_PRICE"),
    ("p_gounthos", "t1", "PARTY_OF"), ("p_atari", "t1", "PARTY_OF"),
    ("p_atreas", "t1", "PARTY_OF"), ("p_buyer", "t1", "PARTY_OF"),
    ("r_nokyrios", "t1", "PARTY_OF"),
    ("t1", "date", "DATED_TO"),
]}

SPEC["114283"] = {"entities": [
    E("DATE_REF", "ὑπατείας"),
    E("PERSON", "Ὁνωρίου"), E("DATE_REF", "τὸ ι"),
    E("PERSON", "Θεοδοσίου"), E("DATE_REF", "τὸ ϛ"),
    E("DATE_REF", "Φαῶφι κα", None, "date"),
    E("PERSON", "Φλαουΐῳ Ἀντωνίῳ"),
    E("OCCUPATION", "σκρινιαρίῳ"),
    E("OCCUPATION", "κόμητος", "μεγαλοπρεπεστάτου κόμητος"),
    E("PERSON", "Ἰωάννου"),
    E("OCCUPATION", "βοηθοῦ"),
    E("PERSON", "Αὐρήλιος Ἄμμων", None, "p1"),
    E("TRANSACTION", "ὡμολόγησα", None, "t1"),
    E("PERSON", "Αὐρήλιος Ἄμμων"),
    E("CURRENCY", "χρυσοῦ"),
    E("CURRENCY", "νομισμάτιον", None, "nom"),
    E("MONEY_AMOUNT", "ἓν", None, "m1"),
    E("PERSON", "Αὐρήλιος Ἰωάννης"),
    E("OCCUPATION", "ἀναγνώστης"),
], "relations": [("m1", "nom", "HAS_CURRENCY"),
    ("p1", "t1", "PARTY_OF"), ("t1", "date", "DATED_TO")]}

SPEC["115553"] = {"entities": [
    E("PLACE", "Κερκεῦρα"),
    E("PLACE", "Εἰρηναίου\nκλήρου"),
    E("DATE_REF", "ι ἔτους"),
    E("PERSON", "Ἀριστοῦτος"),
    E("PERSON", "Ἀπολλωνίου"),
    E("PLACE", "Ὀξυρύγχων πόλεως"),
    E("PLACE", "Κερκεμοῦνιν"),
    E("PLACE", "Φίλωνος κλήρου"),
    E("PERSON", "Ταβαροῦτος"),
    E("PERSON", "Ὥρου"),
    E("PERSON", "Ἀμόιντος", "καὶ Ἀμόιντος"),
    E("PERSON", "Παποντῶτος"),
    E("PERSON", "Διοδώρου"),
    E("PERSON", "Ταναεσνάως"),
    E("PERSON", "Πτολεμαίου"),
    E("PLACE", "Μερμέρθα"),
    E("PLACE", "Ἀνδρονίκου\nκλήρου"),
    E("DATE_REF", "ἔτους", "κλήρου … ἔτους"),
    E("PLACE", "Ὀξυρύγχων πόλεως"),
    E("PERSON", "Ἀσκλᾶτος Θοώνιος"),
    E("PERSON", "Ταθοωνᾶτος"),
    E("PERSON", "Σαραπίωνος"),
    E("PERSON", "Θοῶνις"),
], "relations": []}

SPEC["1183"] = {"entities": [
    E("DATE_REF", "Ὑπερβερεταίου\nιη"),
    E("PERSON", "Ἀρτεμίδωρος"), E("OCCUPATION", "ἰατρός"),
    E("OCCUPATION", "ἱερεῖς", None, "occ1"), E("QUANTITY", "β", "ἱερεῖς β", "occq1"),
    E("COMMODITY", "Λευκαδίου", None, "c1"), E("UNIT", "κοτύλαι", None, "u1"),
    E("QUANTITY", "η", "κοτύλαι η", "q1"),
    E("DATE_REF", "ιθ", "ιθ Ἀρτεμίδωρος"),
    E("PERSON", "Ἀρτεμίδωρος"), E("OCCUPATION", "ἰατρός"),
    E("PERSON", "Ἀρτεμίδωρος"), E("OCCUPATION", "ἐπιστολογράφος"),
    E("PERSON", "Ἡφαιστίων"),
    E("OCCUPATION", "ἱερεῖς", None, "occ2"), E("QUANTITY", "γ", "ἱερεῖς γ", "occq2"),
    E("COMMODITY", "Λευκαδίου", None, "c2"), E("UNIT", "χοῦς", None, "u2"),
    E("QUANTITY", "α", "χοῦς α", "q2"),
    E("DATE_REF", "κ", "κ Ἀρτεμίδωρος"),
    E("PERSON", "Ἀρτεμίδωρος"), E("PERSON", "Ἡφαιστίων"), E("OCCUPATION", "ἱερεῖς"),
    E("COMMODITY", "οἴνου", None, "c3"), E("UNIT", "κοτύλαι", None, "u3"),
    E("QUANTITY", "η", "κοτύλαι η", "q3"),
    E("DATE_REF", "κα", "κα κατὰ πλοῦν"),
    E("PERSON", "Ἀρτεμιδώρωι"), E("PERSON", "Νικάνδρωι"), E("PERSON", "Θεοδώρωι"),
    E("UNIT", "κοτύλαι", None, "u4"), E("QUANTITY", "δ", "κοτύλαι δ", "q4"),
    E("PERSON", "Ἡροφάντωι"),
    E("UNIT", "κοτύλαι", None, "u5"), E("QUANTITY", "β", "κοτύλαι β", "q5"),
    E("DATE_REF", "κβ", "κβ ἐπὶ τοῦ ὅρμου"),
    E("PERSON", "Ἀρτεμίδωρος"), E("PERSON", "Ἰατροκλῆς"), E("PERSON", "Ἀρτεμίδωρος"),
    E("PERSON", "Δημήτριος"),
    E("UNIT", "χοῦς", None, "u6"), E("QUANTITY", "α", "χοῦς α", "q6"),
    E("PERSON", "Ἡρφάντωι"),
    E("DATE_REF", "κγ", "κγ Ἀρτεμίδωρος"), E("PERSON", "Ἀρτεμίδωρος"),
    E("DATE_REF", "κε", "κε εἰς κατάπλασμα"),
    E("COMMODITY", "κατάπλασμα", None, "c7"),
    E("UNIT", "κοτύλαι", None, "u7"), E("QUANTITY", "ε", "κοτύλαι ε", "q7"),
    E("PERSON", "Ἑρμίας"), E("PERSON", "Δημήτριος"),
    E("UNIT", "κοτύλαι", None, "u8"), E("QUANTITY", "ι", "κοτύλαι ι", "q8"),
    E("PERSON", "Ἡροφάντωι"),
    E("UNIT", "κοτύλαι", None, "u9"), E("QUANTITY", "β", "κοτύλαι β", "q9"),
    E("DATE_REF", "κϛ"),
    E("DATE_REF", "κζ", "κζ Δημητρίωι"), E("PERSON", "Δημητρίωι"),
    E("DATE_REF", "κη", "κη Ἀρτεμιδώρωι"),
    E("PERSON", "Ἀρτεμιδώρωι"), E("OCCUPATION", "ἐπιστολογράφωι"),
    E("OCCUPATION", "ἱερεῦσι"), E("PERSON", "Ἑρμοφάντωι"),
    E("COMMODITY", "Κνιδίου", None, "c10"),
    E("UNIT", "κοτύλαι", None, "u10"), E("QUANTITY", "ϛ", "κοτύλαι ϛ", "q10"),
    E("DATE_REF", "κθ", "κη κθ"),
    E("PERSON", "Πύρων"), E("PERSON", "Ἀμύντας"), E("PERSON", "Πάτρων"),
    E("COMMODITY", "κυβίων", None, "c11"),
    E("UNIT", "κεράμια", None, "u11"), E("QUANTITY", "β", "κεράμια β", "q11"),
    E("COMMODITY", "ἰσχάδων Ῥοδιακῶν", None, "c12"),
    E("UNIT", "κεράμια", None, "u12"), E("QUANTITY", "ε", "κεράμια ε", "q12"),
    E("COMMODITY", "Καυνίων", None, "c13"),
    E("UNIT", "κεράμια", None, "u13"), E("QUANTITY", "ε", "κεράμια ε", "q13"),
    E("COMMODITY", "τυροὺς Κυθνίους μεγάλους", None, "c14"),
    E("QUANTITY", "β", "μεγάλους β", "q14"),
    E("COMMODITY", "Ῥηναίους", None, "c15"), E("QUANTITY", "κ", "Ῥηναίους κ", "q15"),
    E("PERSON", "Ἀμύντου"),
    E("COMMODITY", "χλαμὺς\nπροβατεία"),
    E("COMMODITY", "οἴνου Χίου", None, "c16"),
    E("UNIT", "κεράμια", None, "u16"), E("QUANTITY", "β", "κεράμια β", "q16"),
], "relations": [
    ("occ1", "occq1", "HAS_QUANTITY"), ("occ2", "occq2", "HAS_QUANTITY"),
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("c2", "q2", "HAS_QUANTITY"), ("q2", "u2", "HAS_UNIT"),
    ("c3", "q3", "HAS_QUANTITY"), ("q3", "u3", "HAS_UNIT"),
    ("q4", "u4", "HAS_UNIT"), ("q5", "u5", "HAS_UNIT"), ("q6", "u6", "HAS_UNIT"),
    ("c7", "q7", "HAS_QUANTITY"), ("q7", "u7", "HAS_UNIT"),
    ("q8", "u8", "HAS_UNIT"), ("q9", "u9", "HAS_UNIT"),
    ("c10", "q10", "HAS_QUANTITY"), ("q10", "u10", "HAS_UNIT"),
    ("c11", "q11", "HAS_QUANTITY"), ("q11", "u11", "HAS_UNIT"),
    ("c12", "q12", "HAS_QUANTITY"), ("q12", "u12", "HAS_UNIT"),
    ("c13", "q13", "HAS_QUANTITY"), ("q13", "u13", "HAS_UNIT"),
    ("c14", "q14", "HAS_QUANTITY"), ("c15", "q15", "HAS_QUANTITY"),
    ("c16", "q16", "HAS_QUANTITY"), ("q16", "u16", "HAS_UNIT"),
]}

SPEC["11974"] = {"entities": [
    E("TRANSACTION", "ὁμολογία", None, "t1"),
    E("PERSON", "Παΰνχιος", None, "p1a"),
    E("PERSON_ROLE", "τῆς γυναικὸς", None, "p1b"),
    E("PERSON", "Πετεσοῦχον", None, "p1c"),
    E("CURRENCY", "δραχμῶν", None, "d1"), E("MONEY_AMOUNT", "ξδ", None, "m1"),
    E("CURRENCY", "ὀβολοὶ", None, "o1"), E("MONEY_AMOUNT", "ιε", None, "m2"),
    E("TRANSACTION", "ὁμολογία", None, "t2"),
    E("PERSON", "Ὀρσεῦτος", None, "p2a"),
    E("PERSON_ROLE", "τῆς γυναικὸς", None, "p2b"),
    E("PERSON", "Μαρεῦν", None, "p2c"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "δραχμῶν", None, "d2"), E("MONEY_AMOUNT", "κ", "δραχμῶν κ.", "m3"),
    E("CURRENCY", "ὀβολοὶ", None, "o2"), E("MONEY_AMOUNT", "η", "ὀβολοὶ η", "m4"),
    E("TRANSACTION", "μίσθωσις", None, "t3"),
    E("PERSON", "Ἡρακλήου", None, "p3a"),
    E("PERSON", "Δίδυμον Πασιουάνιος", None, "p3b"),
    E("COMMODITY", "ἀράκου", None, "c1"),
    E("UNIT", "ἀρούρης", None, "u1"), E("QUANTITY", "α", "ἀρούρης α", "q1"),
    E("FRACTION", "𐅵"),
    E("TRANSACTION", "ὁμολογία", None, "t4"),
    E("PERSON", "Θαυβάστεως", None, "p4a"),
    E("PERSON", "Τιεσιῆσιν", None, "p4b"),
    E("CURRENCY", "δραχμῶν", None, "d3"), E("MONEY_AMOUNT", "σ", "δραχμῶν σ", "m5"),
    E("PERSON", "Θερμοῦθιν"),
    E("COMMODITY", "κριθῆς", None, "c2"),
    E("UNIT", "ἀρτάβης", None, "u2"), E("QUANTITY", "α", "ἀρτάβης α", "q2"),
    E("TRANSACTION", "μίσθωσις", None, "t5"),
    E("PERSON", "Μάρωνος", None, "p5a"),
    E("PERSON", "Παποντῶν", None, "p5b"),
    E("UNIT", "ἀρουρῶν", None, "u3"), E("QUANTITY", "ια", "ἀρουρῶν ια", "q3"),
    E("CURRENCY", "δραχμαὶ", None, "d4"), E("MONEY_AMOUNT", "ϛ", "δραχμαὶ ϛ", "m6"),
    E("TRANSACTION", "μίσθωσις", None, "t6"),
    E("PERSON", "Ἡρᾶτος", None, "p6a"),
    E("PERSON", "Πάτρωνα", None, "p6b"),
    E("COMMODITY", "χλωρῶν", None, "c3"),
    E("UNIT", "ἀρουρῶν", None, "u4"), E("QUANTITY", "δ", "ἀρουρῶν δ", "q4"),
    E("TRANSACTION", "μίσθωσις", None, "t7"),
    E("PERSON", "Ψοσνεῦτος", None, "p7a"),
    E("PERSON", "Κρονίωνα", None, "p7b"),
    E("COMMODITY", "χόρτου", None, "c4"),
    E("UNIT", "ἀρουρῶν", None, "u5"), E("QUANTITY", "γ", "ἀρουρῶν γ", "q5"),
    E("COMMODITY", "χλωρῶν", None, "c5"),
    E("UNIT", "ἀρουρῶν", None, "u6"), E("QUANTITY", "γ", "ἀρουρῶν γ", "q6"),
    E("UNIT", "ἀρουρῶν", None, "u7"), E("QUANTITY", "ϛ", "ἀρουρῶν ϛ", "q7"),
    E("TRANSACTION", "δάνειον", None, "t8"),
    E("PERSON", "Μάρωνος", None, "p8a"),
    E("PERSON", "Ὀρσεῦν", None, "p8b"),
    E("PERSON_ROLE", "τὴν γυναῖκα", None, "p8c"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "δραχμῶν", None, "d5"), E("MONEY_AMOUNT", "μϛ", None, "m7"),
    E("CURRENCY", "ὀβολοὶ", None, "o3"), E("MONEY_AMOUNT", "ιδ", None, "m8"),
], "relations": [
    ("p1a", "t1", "PARTY_OF"),
    ("p1b", "t1", "PARTY_OF"),
    ("p1c", "t1", "PARTY_OF"),
    ("p2a", "t2", "PARTY_OF"),
    ("p2b", "t2", "PARTY_OF"),
    ("p2c", "t2", "PARTY_OF"),
    ("p3a", "t3", "PARTY_OF"),
    ("p3b", "t3", "PARTY_OF"),
    ("p4a", "t4", "PARTY_OF"),
    ("p4b", "t4", "PARTY_OF"),
    ("p5a", "t5", "PARTY_OF"),
    ("p5b", "t5", "PARTY_OF"),
    ("p6a", "t6", "PARTY_OF"),
    ("p6b", "t6", "PARTY_OF"),
    ("p7a", "t7", "PARTY_OF"),
    ("p7b", "t7", "PARTY_OF"),
    ("p8a", "t8", "PARTY_OF"),
    ("p8b", "t8", "PARTY_OF"),
    ("p8c", "t8", "PARTY_OF"),
    ("m1", "d1", "HAS_CURRENCY"), ("m2", "o1", "HAS_CURRENCY"),
    ("m3", "d2", "HAS_CURRENCY"), ("m4", "o2", "HAS_CURRENCY"),
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("m5", "d3", "HAS_CURRENCY"),
    ("c2", "q2", "HAS_QUANTITY"), ("q2", "u2", "HAS_UNIT"),
    ("q3", "u3", "HAS_UNIT"), ("m6", "d4", "HAS_CURRENCY"),
    ("c3", "q4", "HAS_QUANTITY"), ("q4", "u4", "HAS_UNIT"),
    ("c4", "q5", "HAS_QUANTITY"), ("q5", "u5", "HAS_UNIT"),
    ("c5", "q6", "HAS_QUANTITY"), ("q6", "u6", "HAS_UNIT"),
    ("q7", "u7", "HAS_UNIT"),
    ("m7", "d5", "HAS_CURRENCY"), ("m8", "o3", "HAS_CURRENCY"),
]}

SPEC["12164"] = {"entities": [
    E("PERSON", "Ἡρακλείδης Ἡρακλείδου", None, "p1"),
    E("PERSON", "Κρονίωνι Ἀπίωνος", None, "p2"), E("OCCUPATION", "νομογράφωι"),
    E("PLACE", "Τεβτύνεως"),
    E("TRANSACTION", "ὁμολογῶ", None, "t1"),
    E("PERSON", "Ἡρακλείδην νεώτερον\nΜάρωνος"),
    E("UNIT", "ἀρουρῶν", None, "u1"), E("QUANTITY", "τριῶν", None, "q1"),
    E("FRACTION", "ἡμίσους"),
    E("PERSON", "Ἡρώδου τοῦ καὶ Ἡρακλείδου\nΛυσιμάχου"),
    E("DATE_REF", "ἔτους ὀγδόου", None, "date"),
    E("PERSON", "Τιβερίου Κλαυδίου Καίσαρος\nΣεβαστοῦ Γερμανικοῦ\nΑὐτοκράτορος"),
    E("DATE_REF", "Φαρμοῦθι ιδ"),
], "relations": [("q1", "u1", "HAS_UNIT"),
    ("p1", "t1", "PARTY_OF"), ("p2", "t1", "PARTY_OF"), ("t1", "date", "DATED_TO")]}

SPEC["12583"] = {"entities": [
    E("DATE_REF", "ἔτους τρεισκαιδεκάτου", None, "date"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος Τίτου Αἰλίου Ἁδριανοῦ Ἀντωνίνου Σεβαστοῦ\nΕὐσεβοῦς"),
    E("DATE_REF", "μηνὸς Σεβαστοῦ κζ"), E("DATE_REF", "Θὼθ κζ"),
    E("PLACE", "Ἱερᾷ Νήσῳ"), E("PLACE", "Ἡρακλείδου μερίδος"), E("PLACE", "Ἀρσινοΐτου νομοῦ"),
    E("TRANSACTION", "ὁμολογεῖ", None, "t1"),
    E("PERSON", "Πτολεμαὶς Χαιρήμονος τοῦ Χαιρήμονος", None, "p_seller"),
    E("PLACE", "ἀμφόδου Φρεμεὶ"),
    E("AGE", "πεντήκοντα ὀκτὼ"),
    E("PERSON", "Κέλερος Ἀφροδισίου"),
    E("PERSON", "Ἰουλίῳ Μαξίμῳ", None, "p_lender"),
    E("PERSON", "Πτολεμαΐδα"),
    E("PERSON", "Ἰουλίου Μαξίμου"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "δραχμὰς", None, "dr"),
    E("MONEY_AMOUNT", "ὀκτακοσίας", None, "m1"),
    E("PERSON", "Ἰούλιον Μάξιμον"),
    E("PERSON", "Πτολεμαΐδι"),
    E("PLACE", "κώμην Κερκεσοῦχαν"),
    E("UNIT", "ἀρουρῶν", None, "u1"), E("QUANTITY", "τεσσάρων", None, "q1"),
    E("UNIT", "ἀρουρῶν", None, "u2"), E("QUANTITY", "ἑπτὰ", None, "q2"),
    E("DATE_REF", "τρεισκαιδεκάτου ἔτους"),
    E("PERSON", "Ἀντωνίνου Καίσαρος"),
    E("PERSON", "Πτολεμαΐδα"),
    E("PERSON", "Ἰουλίῳ Μαξίμῳ"),
    E("UNIT", "ἀρούρας", None, "u3"), E("QUANTITY", "τέσσαρας", None, "q3"),
], "relations": [
    ("m1", "dr", "HAS_CURRENCY"),
    ("q1", "u1", "HAS_UNIT"), ("q2", "u2", "HAS_UNIT"), ("q3", "u3", "HAS_UNIT"),
    ("p_seller", "t1", "PARTY_OF"), ("p_lender", "t1", "PARTY_OF"),
    ("t1", "date", "DATED_TO"),
]}

SPEC["12593"] = {"entities": [
    E("COMMODITY", "νομῆς ὑπολόγων καὶ ῥαχοῦ", None, "c1"),
    E("PLACE", "Ψενύρεως"),
    E("CURRENCY", "δραχμῶν", None, "d1"), E("MONEY_AMOUNT", "κ", "δραχμῶν κ.", "m1"),
    E("PERSON", "Ἁρυώθου", None, "p1"),
    E("PLACE", "Ψενύρεως"),
    E("TRANSACTION", "μισθώσασθαι", None, "t1"),
    E("DATE_REF", "ιη ἔτος"),
    E("PERSON", "Ἁδριανοῦ Καίσαρος"),
    E("COMMODITY", "νομὴν ὑπολόγων καὶ ῥαχοῦ", None, "c2"),
    E("PLACE", "Ψενύρεως"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "δραχμὰς", None, "d2"), E("MONEY_AMOUNT", "εἴκοσι", None, "m2"),
    E("PERSON", "Ἁρυώθης"),
    E("DATE_REF", "ἔτους ιζ", None, "date"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος Τραϊανοῦ\nἉδριανοῦ Σεβαστοῦ"),
    E("DATE_REF", "Ἐπεὶφ η"),
    E("PERSON", "Βησαρίων"), E("OCCUPATION", "ὑπηρέτης"),
], "relations": [
    ("m1", "d1", "HAS_CURRENCY"), ("c1", "m1", "HAS_PRICE"),
    ("m2", "d2", "HAS_CURRENCY"), ("c2", "m2", "HAS_PRICE"),
    ("p1", "t1", "PARTY_OF"), ("t1", "date", "DATED_TO"),
]}

SPEC["12769"] = {"entities": [
    E("PERSON", "Στοτοῆτι Στοτοήτεως", None, "p1"),
    E("PERSON", "Ὥρου τοῦ Τεσενούφεως τοῦ Τεσενούφεως", None, "p2"),
    E("TRANSACTION", "μισθώσασθαι", None, "t1"),
    E("PLACE", "κώμῃ Ἡρακλείᾳ"),
    E("COMMODITY", "ἐλαιουργεῖον"),
    E("DATE_REF", "μηνὸς Σωτηρίου νουμηνίας"),
    E("DATE_REF", "πεντεκαιδεκάτου ἔτους", None, "date"),
    E("PERSON", "Αὐτοκράτορος\nΚαίσαρος Δομιτιανοῦ Σεβαστοῦ Γερμανικοῦ"),
    E("TAX_TERM", "φόρου"),
    E("COMMODITY", "ἐλαίου ῥαφανίνου", None, "c1"),
    E("UNIT", "μετρητῶν", None, "u1"), E("QUANTITY", "δύο", None, "q1"),
    E("COMMODITY", "ἐλαίου ῥαφανίνου"),
    E("PERSON", "Στοτοήτεως"),
], "relations": [("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("p1", "t1", "PARTY_OF"), ("p2", "t1", "PARTY_OF"), ("t1", "date", "DATED_TO")]}

SPEC["128477"] = {"entities": [
    E("DATE_REF", "Παῦνι κθ"),
    E("DATE_REF", "Ἐπὶφ θ"), E("PLACE", "Καμμέτος"),
    E("COMMODITY", "σίτου", None, "c1"), E("UNIT", "ἀρτάβαι", None, "u1"),
    E("QUANTITY", "γ", "ἀρτάβαι γ", "q1"), E("FRACTION", "𐅷"),
    E("DATE_REF", "Ἐπὶφ ι"), E("PLACE", "Ἰερημίου"),
    E("COMMODITY", "σίτου", None, "c2"), E("UNIT", "ἀρτάβαι", None, "u2"),
    E("FRACTION", "𐅷"),
    E("DATE_REF", "Ἐπὶφ ιβ"), E("PLACE", "Τρακωνε"),
    E("COMMODITY", "σίτου", None, "c3"), E("UNIT", "ἀρτάβαι", None, "u3"),
    E("QUANTITY", "ε", "ἀρτάβαι ε", "q3"),
    E("DATE_REF", "Ἐπὶφ ιε"),
    E("PLACE", "Καμμέτος"), E("PLACE", "Τρακωνη"), E("PLACE", "Τιμε"),
    E("COMMODITY", "σίτου", None, "c4"), E("UNIT", "ἀρτάβαι", None, "u4"),
    E("QUANTITY", "δ", "ἀρτάβαι δ", "q4"),
    E("DATE_REF", "Ἐπὶφ κθ"),
    E("COMMODITY", "σίτου", None, "c5"), E("UNIT", "ἀρτάβαι", None, "u5"),
    E("QUANTITY", "β", "ἀρτάβαι β", "q5"),
    E("PLACE", "Μοιρῶν"),
    E("COMMODITY", "σίτου", None, "c6"), E("UNIT", "ἀρτάβαι", None, "u6"),
    E("FRACTION", "𐅷"),
], "relations": [
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("c3", "q3", "HAS_QUANTITY"), ("q3", "u3", "HAS_UNIT"),
    ("c4", "q4", "HAS_QUANTITY"), ("q4", "u4", "HAS_UNIT"),
    ("c5", "q5", "HAS_QUANTITY"), ("q5", "u5", "HAS_UNIT"),
]}

SPEC["13473"] = {"entities": [
    E("PERSON", "Τασεῦς"), E("OCCUPATION", "ἀρχιπροφήτης"),
    E("PLACE", "Ἡλίου πόλει"),
    E("PERSON", "Ὥρου Ἀρήιτος"), E("OCCUPATION", "ἱερέως"),
    E("PERSON", "Νεβωνυχος Ἰφύνους"), E("OCCUPATION", "ἱερεὺς"),
    E("OCCUPATION", "δευτεροστολιστὴς"),
    E("PERSON", "Πετοσορᾶπις Πετοσοράπιος"), E("OCCUPATION", "λεσώνης"),
    E("PERSON", "Σερῆνος Μενθώτου"), E("OCCUPATION", "ἱερεῖς"),
    E("PERSON", "Μάρωνι Πακήβκεως τοῦ καὶ Ζωσίμου"), E("OCCUPATION", "ἱερεῖ"),
    E("PLACE", "κώμης Τεπτύνεως"), E("PLACE", "Πολέμωνος μερίδος"),
    E("PLACE", "Ἀρσινοείτου νομοῦ"),
    E("PERSON", "Διοσκόρου\nἈπολλωνίου"),
    E("COMMODITY", "βυσσοῦ", None, "c1"),
    E("UNIT", "πήχεις", None, "u1"), E("QUANTITY", "εἴκοσι", None, "q1"),
    E("DATE_REF", "ἔτους ιθ"),
    E("PERSON", "Μάρκου Αὐρηλίου\nἈντωνίνου"),
    E("PERSON", "Πουβλίου Σεπτιμίου Γέτα"),
], "relations": [("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT")]}

SPEC["13487"] = {"entities": [
    E("PERSON", "Ἀντωνίωι Μοσχιανῶι Οὐλπιανῶι"), E("OCCUPATION", "ἐπιστρατηγῶι"),
    E("PERSON", "Θέωνος Μάρωνος"), E("PLACE", "Ἀρσινοίτου"),
    E("PERSON", "Ἰνσταντίου Μοδεράτου"),
    E("COMMODITY", "πυροῦ"),
    E("DATE_REF", "λα ἔτει μηνὶ Μεσορὴ"),
    E("OCCUPATION", "γραμματέων"),
], "relations": []}

SPEC["144620"] = {"entities": [
    E("PERSON", "Ψενθώτης"), E("OCCUPATION", "κονδούκτωρι"),
    E("PLACE", "Διδύμου ὑδρεύματος"),
    E("PERSON", "Κάλβῳ"), E("PERSON", "Σιουῆτι"),
    E("COMMODITY", "κριθῆς", None, "c1"),
    E("UNIT", "μάτια", None, "u1"), E("QUANTITY", "τέσσαρα", None, "q1"),
    E("QUANTITY", "δ", "γίνεται δ"),
    E("COMMODITY", "ἄρτων", None, "c2"),
    E("UNIT", "ζεύγη", None, "u2"), E("QUANTITY", "ὀκτὼ", None, "q2"),
    E("QUANTITY", "η", "γίνεται η"),
], "relations": [
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("c2", "q2", "HAS_QUANTITY"), ("q2", "u2", "HAS_UNIT"),
]}

SPEC["144885"] = {"entities": [
    E("PERSON", "Ἰούλιος"), E("PERSON", "Ἀντωνίωι"),
    E("CURRENCY", "στατῆρα"),
    E("PERSON", "Οὐαλερίου"),
    E("CURRENCY", "ὀβόλους", None, "ob"), E("MONEY_AMOUNT", "ε", "ὀβόλους ε", "m1"),
    E("PERSON", "Κέλερος"), E("OCCUPATION", "ἱππέως"),
    E("COMMODITY", "ἁλός"),
], "relations": [("m1", "ob", "HAS_CURRENCY")]}


# ---------------------------------------------------------------------------
# Batch documents 16-30 (index 15-29). Same method, calibrated to guidelines
# v0.2: TRANSACTION anchors, PERSON_ROLE for unnamed/role parties, rulers split
# out of DATE_REF, mothers annotated as PERSON, genitive-named parcels PLACE.
# ---------------------------------------------------------------------------

SPEC["14562"] = {"entities": [  # census/epikrisis age-list
    E("DATE_REF", "β ἔτους"),
    E("DATE_REF", "ια ἔτους", "ια ἔτους. οἱ"),
    E("DATE_REF", "τὸ η ἔτος"),
    E("AGE", "ιβ", "ἐτῶν ιβ"),
    E("AGE", "ιδ", "ἐτῶν ιδ"),
    E("PERSON", "Ὀννῶφρις Τιθοήους"), E("PERSON", "Ἐσενεῦτος"),
    E("PERSON", "Ταακείους"),
    E("PERSON", "Παποντῶς Νεφερῶτος"), E("PERSON", "Ἡρῶτος"),
    E("DATE_REF", "θ ἔτει"),
    E("PERSON", "Κιαλῆς ὃς καὶ Νεφερῶς Νεφερῶτος"), E("PERSON", "Ταήσιος"),
    E("DATE_REF", "ια ἔτους", "ια ἔτους. …"),
    E("DATE_REF", "ι ἔτους", "ι ἔτους. ο…"),
    E("DATE_REF", "ι ἔτους", "ι ἔτους ……"),
    E("DATE_REF", "θ ἔτους"),
], "relations": []}

SPEC["15074"] = {"entities": [  # livestock (camel) declaration + purchase
    E("PLACE", "Σοκνοπαίου Νήσου"),
    E("COMMODITY", "κάμηλος", "Σοκνοπαίου Νήσου κάμηλος", "c0"),
    E("QUANTITY", "α", "κάμηλος α\n", "q0"),
    E("PERSON", "Θεοδώρωι"), E("OCCUPATION", "στρατηγῷ"),
    E("PERSON", "Τειμαγένει"), E("OCCUPATION", "βασιλικῷ γραμματεῖ"),
    E("PLACE", "Ἀρσινοίτου"), E("PLACE", "Ἡρακλείδου μερίδος"),
    E("PERSON", "Ἑκύσιος Ὥρου", None, "declarant"),
    E("PLACE", "κώμης Σοκνοπαίου Νήσου"),
    E("DATE_REF", "κ ἔτους"),
    E("COMMODITY", "θρεμμάτων"),
    E("TRANSACTION", "ἠγόρασα", None, "t1"),
    E("PERSON", "Πτολεμαίου\nΛεωνίδου", None, "seller"),
    E("PLACE", "κώμης Καρανίδος"),
    E("COMMODITY", "κάμηλον", None, "c1"), E("QUANTITY", "μίαν", None, "q1"),
    E("OCCUPATION", "στρατηγῷ", "παρὰ στρατηγῷ"),
    E("OCCUPATION", "βοηθοῦ", "βοηθοῦ κάμηλος"),
    E("COMMODITY", "κάμηλος", "βοηθοῦ κάμηλος", "c2"), E("QUANTITY", "α", "κάμηλος α Μεχεὶρ", "q2"),
    E("DATE_REF", "Μεχεὶρ γ", "κάμηλος α Μεχεὶρ γ"),
    E("OCCUPATION", "βασιλικῷ", "παρὰ βασιλικῷ κάμηλος"),
    E("COMMODITY", "κάμηλος", "βασιλικῷ κάμηλος", "c3"), E("QUANTITY", "α", "κάμηλος α Μεχεὶρ", "q3"),
    E("DATE_REF", "Μεχεὶρ γ", "κάμηλος α Μεχεὶρ γ"),
    E("PERSON", "Πτολεμαῖος", "Πτολεμαῖος·"),
    E("OCCUPATION", "βασιλικῷ γραμματεῖ", "παρὰ βασιλικῷ γραμματεῖ"),
    E("PERSON", "Νεῖλος ὁ καὶ Σαπ"), E("OCCUPATION", "ἀγορανομήσας"),
    E("PERSON", "Ἰσιδώρου"), E("OCCUPATION", "βοηθοῦ", "Ἰσιδώρου βοηθοῦ"),
], "relations": [
    ("c0", "q0", "HAS_QUANTITY"), ("c1", "q1", "HAS_QUANTITY"),
    ("c2", "q2", "HAS_QUANTITY"), ("c3", "q3", "HAS_QUANTITY"),
    ("declarant", "t1", "PARTY_OF"), ("seller", "t1", "PARTY_OF"),
]}

SPEC["15090"] = {"entities": [  # property registration by a woman with guardian
    E("DATE_REF", "Μεχεὶρ κ", "Μεχεὶρ κ\n"),
    E("PERSON", "Ἀπολλωνίῳ"), E("OCCUPATION", "γεγυμνασιαρχηκότι"),
    E("PERSON", "Νικολάῳ"), E("OCCUPATION", "βιβλιοφύλαξι ἐνκτήσεων"),
    E("PLACE", "Ἀρσινοΐτου"),
    E("PERSON", "Στοτοήτιος", "παρὰ Στοτοήτιος", "woman"),
    E("PERSON", "Στοτοήτιος τοῦ Ὥρου"),
    E("PLACE", "Σοκνοπαίου Νήσου"), E("PLACE", "Ἡρακλείδου μερίδος"),
    E("PERSON_ROLE", "μετὰ κυρίου τοῦ ἀνδρὸς"),
    E("PERSON", "Στοτοήτιος\nτοῦ Νεστνήφιος"),
    E("PERSON", "Ἀμμωνίου"), E("PERSON", "Σαραπίωνος"),
    E("DATE_REF", "ζ ἔτει", None, "date1"), E("PERSON", "Νέρωνος"),
    E("TRANSACTION", "ἐκτησάμην", None, "t1"),
    E("FRACTION", "ἥμισυ"), E("COMMODITY", "οἰκίας", None, "house"),
    E("PRICE_TERM", "τιμῆς"), E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "δραχμῶν", None, "dr"),
    E("MONEY_AMOUNT", "ἑκατὸν τεσσαράκοντα", None, "m1"),
    E("PERSON", "Ἐριέως\nτοῦ Ὀννώφριος τοῦ Ἁρπαγάθου", None, "seller"),
    E("OCCUPATION", "ἱερέως"),
    E("DATE_REF", "ἔτους δεκάτου"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος\nΟὐεσπασιανοῦ Σεβαστοῦ"),
    E("DATE_REF", "Μεχεὶρ κ", "Σεβαστοῦ Μεχεὶρ κ"),
], "relations": [
    ("m1", "dr", "HAS_CURRENCY"), ("house", "m1", "HAS_PRICE"),
    ("woman", "t1", "PARTY_OF"), ("seller", "t1", "PARTY_OF"),
    ("t1", "date1", "DATED_TO"),
]}

SPEC["15362"] = {"entities": [  # lease of an oil-press
    E("DATE_REF", "ὑπατείαν"), E("PERSON", "Ὁνωρίου"), E("DATE_REF", "τὸ θ"),
    E("PERSON", "Θεοδοσίου"), E("DATE_REF", "τὸ δ"),
    E("DATE_REF", "Θὼθ ιδ"),
    E("PERSON", "Φλαουΐῳ Λιμενίῳ", None, "lessor"),
    E("PLACE", "Ὀξυρυγχιτῶν πόλεως"),
    E("PERSON", "Αὐρηλίου Πέτρου", None, "lessee"),
    E("OCCUPATION", "ἐλαιουργοῦ"),
    E("TRANSACTION", "μισθώσασθαι", None, "t1"),
    E("DATE_REF", "Θὼθ", "μηνὸς Θὼθ τοῦ"),
    E("DATE_REF", "ἑνδεκάτης ἰνδικτίωνος"),
    E("PLACE", "Παρεμβολῆς"),
    E("COMMODITY", "ἐλαιούργιον"),
    E("TAX_TERM", "φόρου"),
    E("COMMODITY", "ἐλαίου ῥαφανίνου", None, "c1"),
    E("UNIT", "ξέστας", None, "u1"), E("QUANTITY", "ἑκατὸν εἴκοσι", "ξέστας ἑκατὸν εἴκοσι", "q1"),
    E("UNIT", "ἀρτάβας", None, "u2"),
    E("QUANTITY", "ἑκατὸν εἴκοσι", "ἀρτάβας ἑκατὸν εἴκοσι", "q2"),
], "relations": [
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("q2", "u2", "HAS_UNIT"),
    ("lessor", "t1", "PARTY_OF"), ("lessee", "t1", "PARTY_OF"),
]}

SPEC["15382"] = {"entities": [  # list of councillors present
    E("DATE_REF", "λ τοῦ ὄντος μηνὸς Θὼθ"),
    E("DATE_REF", "ιδ ἔτους"),
    E("PERSON", "Ἀντωνίνου Καίσαρος"),
    E("PERSON", "Πολυδεύκης Ἡρακλείου"),
    E("PERSON", "Διονύσιος Ὅπλωνος"),
    E("PERSON", "Ἀνδρέας Ἀσκληπιάδου"),
    E("PERSON", "Ἰούλιος Νουμισιανὸς"),
    E("PERSON", "Ἡρακλείδης Γαίου"),
    E("PERSON", "Σωτάδης Διοδώρου"),
    E("PERSON", "Ἀθηνόδωρος ὁ καὶ Τούρβων"),
    E("PERSON", "Ἡρακλείου Ἀπολλοδώρου"),
    E("PERSON", "Εὐτυχίδης Σαραπίωνος"),
], "relations": []}

SPEC["15454"] = {"entities": [  # loan / release (homologia)
    E("DATE_REF", "ὑπατείας"),
    E("PERSON", "Φλαουίων\nἈναστασίου"),
    E("PERSON", "Ῥούφου"),
    E("DATE_REF", "Ἁθὺρ ιβ"),
    E("DATE_REF", "α\nἰνδικτίονος"),
    E("PLACE", "κώμῃ Βουσίρει"),
    E("PERSON", "Αὐρήλιος\nἈβραὰμ υἱὸς\nΕὐδαίμονος", None, "p1"),
    E("PLACE", "κώμης Βουσίρεως"),
    E("PLACE", "Ἡρακλεουπολίτου νομοῦ"),
    E("PERSON", "Αὐρηλίῳ\nΔωροθέῳ υἱῷ Ψίωλ", None, "p2"),
    E("TRANSACTION", "ὁμολογῶ", None, "t1"),
    E("MONEY_AMOUNT", "κ", "τῶν κ κερατίων", "m1"), E("CURRENCY", "κερατίων", None, "cur1"),
    E("CURRENCY", "νομίσματα", "τὰ νομίσματα β\n", "cur2"), E("MONEY_AMOUNT", "β", "νομίσματα β\n", "m2"),
    E("CURRENCY", "νομίσματα", "ἐδεξάμην\nτὰ νομίσματα β", "cur3"), E("MONEY_AMOUNT", "β", "τὰ νομίσματα β καὶ", "m3"),
    E("PERSON", "Αὐρήλιος\nἌεις Κουαντίνου"),
    E("PERSON", "Ἄειτος Κουαντίνου"),
    E("DATE_REF", "α ἰνδικτίονος"),
], "relations": [
    ("m1", "cur1", "HAS_CURRENCY"), ("m2", "cur2", "HAS_CURRENCY"),
    ("m3", "cur3", "HAS_CURRENCY"),
    ("p1", "t1", "PARTY_OF"), ("p2", "t1", "PARTY_OF"),
]}

SPEC["15488"] = {"entities": [  # loan of silver (blind); borrower's name lost to lacuna
    E("DATE_REF", "ὑπατείαν", None, "date"),
    E("PERSON", "Κωνσταντίνου"), E("PERSON", "Λικιννιανοῦ"),
    E("DATE_REF", "τὸ γ"),
    E("PERSON", "Πτολέμας"),
    E("PLACE", "Ὀξυρυγχίτου νομοῦ"),
    E("PLACE", "Ὀξυρυγχιτῶν πόλεως"),
    E("TRANSACTION", "ὁμολογῶ", None, "t1"),
    E("CURRENCY", "ἀργυρίου"),
    E("CURRENCY", "τάλαντα", None, "cur1"), E("MONEY_AMOUNT", "ἐννέα", None, "m1"),
    E("CURRENCY", "δραχμὰς", None, "cur2"),
    E("DATE_REF", "η ἔτους"), E("DATE_REF", "ϛ ἔτους"),
    E("CURRENCY", "μνᾶς"),
], "relations": [
    ("m1", "cur1", "HAS_CURRENCY"),
    ("t1", "date", "DATED_TO"),  # parties are lost to the lacuna; only the date survives
]}

SPEC["15887"] = {"entities": [  # payment order (blind)
    E("DATE_REF", "κδ ἔτους"), E("PERSON", "Ἀντωνίνου Καίσαρος"),
    E("DATE_REF", "Φαμενὼθ"),
    E("PERSON", "Ἰουλίων Θέωνος"), E("OCCUPATION", "ἐνάρχου\nἀρχιδικαστοῦ"),
    E("PERSON", "Θέωνος τοῦ καὶ\nΤρύφωνος"),
    E("TAX_TERM", "ὀψωνίου"),
    E("DATE_REF", "μηνὸς Ἁδριανοῦ"), E("DATE_REF", "Μεχείρ", "ἕως Μεχείρ"),
    E("CURRENCY", "δραχμὰς", None, "cur1"), E("MONEY_AMOUNT", "ἑκατὸν εἴκοσι", None, "m1"),
    E("CURRENCY", "δραχμαὶ", None, "cur2"), E("MONEY_AMOUNT", "ρκ", "δραχμαὶ ρκ", "m2"),
    E("CURRENCY", "δραχμὰς", "τὰς δραχμὰς", "cur3"), E("MONEY_AMOUNT", "ρκ", "δραχμὰς ρκ", "m3"),
], "relations": [
    ("m1", "cur1", "HAS_CURRENCY"), ("m2", "cur2", "HAS_CURRENCY"),
    ("m3", "cur3", "HAS_CURRENCY"),
]}

SPEC["16001"] = {"entities": [  # lease / sworn cultivation undertaking (blind)
    E("DATE_REF", "ὑπατείαν"),
    E("PERSON", "Λικινίου Σεβαστοῦ"), E("DATE_REF", "τὸ ϛ"),
    E("PERSON", "Λικινίου\nτοῦ ἐπιφανεστάτου Καίσαρος"), E("DATE_REF", "τὸ β"),
    E("PERSON", "Οὐάλεντι"),
    E("PERSON", "Αὐρήλιοι Πανοτβέως Ὀρσενούφιος", None, "p1"), E("PERSON", "Ταᾶτος"),
    E("PERSON", "Ἀφύγχις Ἀφυγχίου", None, "p2"), E("PERSON", "Θαήσιος"),
    E("PLACE", "κώμης Ποσόμπους"),
    E("PLACE", "Ὀξυρυγχίτου νομοῦ"),
    E("PERSON", "Κοπρεὺς Διοσκόρου", None, "p3"), E("PERSON", "Τενγώγιος"),
    E("PLACE", "Ποσόμπους κώμῃ"),
    E("TRANSACTION", "ὁμολογοῦμεν", None, "t1"),
    E("PERSON", "Πανοτβέουν"),
    E("UNIT", "ἀρουρῶν", "τὸν Πανοτβέουν\nἀρουρῶν", "u1"),
    E("QUANTITY", "ἑπτὰ", "ἀρουρῶν ἑπτὰ", "q1"), E("FRACTION", "ἡμίσους", "ἑπτὰ ἡμίσους"),
    E("PERSON", "Θερμούθει"), E("PERSON", "Θαισοῦτι"),
    E("PERSON", "Ἀφύγχιον"), E("PERSON", "Κοπρέα"),
    E("UNIT", "ἀρουρῶν", "ἑτέρων ἀρουρῶν", "u2"),
    E("QUANTITY", "ἑπτὰ", "ἑτέρων ἀρουρῶν ἑπτὰ", "q2"), E("FRACTION", "ἡμίσους", "ἀρουρῶν ἑπτὰ ἡμίσους"),
    E("UNIT", "ἀρούρας", None, "u3"), E("QUANTITY", "δεκαπέντε", None, "q3"),
    E("PERSON", "Κορνηλίου"),
    E("PERSON", "Θερμούτιον"), E("PERSON", "Θαισοῦν"),
    E("TAX_TERM", "φόρῳ"),
], "relations": [
    ("q1", "u1", "HAS_UNIT"), ("q2", "u2", "HAS_UNIT"), ("q3", "u3", "HAS_UNIT"),
    ("p1", "t1", "PARTY_OF"), ("p2", "t1", "PARTY_OF"), ("p3", "t1", "PARTY_OF"),
]}

SPEC["16015"] = {"entities": [  # census/epikrisis petition (girl's age)
    E("PERSON", "Αὐρηλίαν Ἀπίαν", None, "girl"),
    E("DATE_REF", "η ἔτος"), E("DATE_REF", "ζ ἔτος", "καὶ ζ ἔτος"),
    E("AGE", "ιη", "ἐτῶν ιη"),
    E("DATE_REF", "ἔτους η", "ἐψεῦσθαι. ἔτους η"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος Γαΐου Αὐρηλίου\nΟὐαλερίου Διοκλητιανοῦ"),
    E("DATE_REF", "ζ ἔτους", "καὶ ζ ἔτους"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος Μάρκου Αὐρηλίου\nΟὐαλερίου Μαξιμιανοῦ"),
    E("DATE_REF", "Παῦνι κζ"),
    E("PERSON", "Αὐρήλιος Σαραπίων", None, "father"),
    E("PERSON", "Παμμένους Παραδείσου"),
    E("PERSON", "Ἀπία", "Παραδείσου Ἀπία", "girl2"), E("PERSON", "Ἰσιδώρας"),
    E("AGE", "ιη", "ἐτῶν ιη\nφυσικὴ"),
    E("PERSON", "Σαραπίωνος", "θυγάτηρ Σαραπίωνος"),
], "relations": []}

SPEC["16219"] = {"entities": [  # Byzantine/Arab-era gold account
    E("PERSON", "Ὡρουγχίῳ"), E("OCCUPATION", "βοηθῷ"),
    E("PERSON", "Μαγίστωρ", "Ι Μαγίστωρ"), E("OCCUPATION", "βοηθὸς λογιστηρίου"),
    E("DATE_REF", "δευτέρας ἰνδικτίονος"),
    E("CURRENCY", "χρυσοῦ", "ὑποδοχῆς δευτέρας ἰνδικτίονος\nχρυσοῦ", "cur1"),
    E("CURRENCY", "νομίσματα", "χρυσοῦ νομίσματα ἓξ", "cur1b"),
    E("MONEY_AMOUNT", "ἓξ", "νομίσματα ἓξ εὔσταθμα", "m1"),
    E("PLACE", "Ἀλεξανδρείας", "εὔσταθμα Ἀλεξανδρείας"),
    E("PERSON", "Βασιλείῳ"), E("OCCUPATION", "βοηθῷ", "Βασιλείῳ βοηθῷ"),
    E("DATE_REF", "α ἰνδικτίονος"),
    E("PERSON", "Βίκτορος Διοσκ"), E("PERSON", "Ἰσιδώρου"),
    E("CURRENCY", "κεράτια", "Ἰσιδώρου κεράτια", "cur2"),
    E("MONEY_AMOUNT", "εἴκοσι τρία", None, "m2"),
    E("PLACE", "Ἀλεξανδρείας", "εἴκοσι τρία Ἀλεξανδρείας"),
    E("PLACE", "μοναστηρίου ἄπα Ἰακκώβου"),
    E("CURRENCY", "νομισμάτων", None, "cur3"), E("MONEY_AMOUNT", "ϛ", "νομισμάτων ϛ", "m3"),
    E("CURRENCY", "κεράτια", "ϛ κεράτια ιζ", "cur4"),
    E("MONEY_AMOUNT", "ιζ", "κεράτια ιζ 𐅵", "m4"), E("FRACTION", "𐅵", "ιζ 𐅵 κεράτια"),
    E("CURRENCY", "νομίσματα", "ὁμοῦ νομίσματα ζ", "cur5"),
    E("MONEY_AMOUNT", "ζ", "νομίσματα ζ κεράτια", "m5"),
    E("CURRENCY", "κεράτια", "νομίσματα ζ κεράτια ιϛ", "cur6"),
    E("MONEY_AMOUNT", "ιϛ", "κεράτια ιϛ 𐅵 Ἀλεξανδρείας\nἀφʼ", "m6"), E("FRACTION", "𐅵", "ιϛ 𐅵 Ἀλεξανδρείας\nἀφʼ"),
    E("PERSON", "Μηνᾷ"), E("OCCUPATION", "ὑποδέκτῃ"),
    E("CURRENCY", "νόμισμα", None, "cur7"), E("MONEY_AMOUNT", "α", "νόμισμα α εὔσταθμον", "m7"),
    E("PERSON", "Μαγίστωρ", "… Μαγίστωρ σὺν"),
    E("OCCUPATION", "βοηθὸς λογιστηρίου", "θεῷ βοηθὸς λογιστηρίου ἐπιδέδωκα"),
    E("PERSON", "Μαγίστωρος"),
    E("DATE_REF", "β ἰνδικτίονος", "Μαγίστωρος β ἰνδικτίονος"),
], "relations": [
    ("m1", "cur1b", "HAS_CURRENCY"), ("m2", "cur2", "HAS_CURRENCY"),
    ("m3", "cur3", "HAS_CURRENCY"), ("m4", "cur4", "HAS_CURRENCY"),
    ("m5", "cur5", "HAS_CURRENCY"), ("m6", "cur6", "HAS_CURRENCY"),
    ("m7", "cur7", "HAS_CURRENCY"),
]}

SPEC["16396"] = {"entities": [  # order to grain-officials to release wheat
    E("PERSON", "Ἰσιδώρα Ἡροδώρου", None, "p1"),
    E("PERSON", "Διονυσίου\nτοῦ καὶ Ὠριγένους Διογένους"),
    E("OCCUPATION", "σιτολόγοις"),
    E("PLACE", "Ἄνω\nτοπαρχίας"),
    E("TRANSACTION", "διαστείλατε", None, "t1"),
    E("COMMODITY", "πυροῦ", None, "c1"),
    E("DATE_REF", "ια ἔτους", "γενήματος ια ἔτους"),
    E("PERSON", "Ἀντωνείνου\nΚαίσαρος", "ια ἔτους Ἀντωνείνου\nΚαίσαρος"),
    E("PERSON", "Ἡραΐδι\nΔιονυσίου", None, "p2"),
    E("UNIT", "ἀρτάβας", None, "u1"), E("QUANTITY", "ἕνδεκα", None, "q1"),
    E("UNIT", "χοίνικας", None, "u2"), E("QUANTITY", "ὀκτώ", None, "q2"),
    E("UNIT", "ἀρτάβαι", None, "u3"), E("QUANTITY", "ια", "ἀρτάβαι ια", "q3"),
    E("UNIT", "χοίνικες", None, "u4"), E("QUANTITY", "η", "χοίνικες η", "q4"),
    E("DATE_REF", "ἔτους ια", "ἔτους ια Ἀντωνείνου"),
    E("PERSON", "Ἀντωνείνου\nΚαίσαρος", "ἔτους ια Ἀντωνείνου\nΚαίσαρος"),
    E("DATE_REF", "Θὼθ", "κυρίου, Θὼθ"),
], "relations": [
    ("c1", "q1", "HAS_QUANTITY"), ("q1", "u1", "HAS_UNIT"),
    ("q2", "u2", "HAS_UNIT"),
    ("q3", "u3", "HAS_UNIT"), ("q4", "u4", "HAS_UNIT"),
    ("p1", "t1", "PARTY_OF"), ("p2", "t1", "PARTY_OF"),
]}

SPEC["16499"] = {"entities": [  # account of purchases/prices (damaged)
    E("DATE_REF", "μῆνα Παῦνι", "διελθόντα μῆνα Παῦνι"),
    E("PRICE_TERM", "τιμὴ", "Παῦνι τιμὴ δραχμαὶ"),
    E("CURRENCY", "δραχμαὶ", "τιμὴ δραχμαὶ ξ", "cur1"), E("MONEY_AMOUNT", "ξ", "δραχμαὶ ξ", "m1"),
    E("PERSON", "Ἰσχυρίωνος Διοσκοῦτος"), E("OCCUPATION", "γεγυμνασιαρχηκότος"),
    E("PLACE", "Ἀρσινοίτου"),
    E("COMMODITY", "γῆς ψιλῶν τόπων"),
    E("PERSON", "Τιβερίου Ποσιδωνίου τοῦ καὶ\nἸσχυρίωνος"),
    E("PERSON", "Κόθυς Ἀλεξανδρέως"),
    E("PLACE", "Ἀλεξανδρείας"),
    E("DATE_REF", "κα ἔτει"), E("DATE_REF", "Παῦνι", "μηνὶ Παῦνι τιμὴ"),
    E("PRICE_TERM", "τιμὴ", "Παῦνι τιμὴ δραχμαὶ ιδ"),
    E("CURRENCY", "δραχμαὶ", "τιμὴ δραχμαὶ ιδ", "cur2"), E("MONEY_AMOUNT", "ιδ", "δραχμαὶ ιδ", "m2"),
    E("CURRENCY", "δραχμαὶ", "δραχμαὶ υμ", "cur3"), E("MONEY_AMOUNT", "υμ", "δραχμαὶ υμ", "m3"),
    E("CURRENCY", "δραχμαὶ", "ζ δραχμαὶ ιϛ", "cur4"), E("MONEY_AMOUNT", "ιϛ", "δραχμαὶ ιϛ", "m4"),
    E("CURRENCY", "δραχμαὶ", "ἀγαθων δραχμαὶ λϛ", "cur5"), E("MONEY_AMOUNT", "λϛ", "δραχμαὶ λϛ", "m5"),
    E("CURRENCY", "δραχμαὶ", "λϛ\nδραχμαὶ ιγ", "cur6"), E("MONEY_AMOUNT", "ιγ", "δραχμαὶ ιγ\n", "m6"),
    E("CURRENCY", "δραχμαὶ", "… δραχμαὶ ιγ", "cur7"), E("MONEY_AMOUNT", "ιγ", "δραχμαὶ ιγ\nεἰς", "m7"),
    E("PERSON", "Πτολεμαίδα"),
    E("PERSON", "Πτολεμαίου τοῦ Πτολεμαίου", "προ Πτολεμαίδα\nΠτολεμαίου τοῦ Πτολεμαίου"),
    E("CURRENCY", "δραχμῶν", "κεφαλαίου δραχμῶν ω", "cur8"), E("MONEY_AMOUNT", "ω", "δραχμῶν ω", "m8"),
    E("CURRENCY", "δραχμῶν", "τόκων δραχμῶν λβ", "cur9"), E("MONEY_AMOUNT", "λβ", "δραχμῶν λβ", "m9"),
    E("CURRENCY", "δραχμαὶ", "δραχμαὶ ωλβ", "cur10"), E("MONEY_AMOUNT", "ωλβ", "δραχμαὶ ωλβ", "m10"),
    E("CURRENCY", "δραχμαὶ", "ωλβ ἐπιδ δραχμαὶ κ", "cur11"), E("MONEY_AMOUNT", "κ", "δραχμαὶ κ\n", "m11"),
    E("PERSON", "Ἀπολλ Ἀνουβίωνος"),
    E("CURRENCY", "δραχμαὶ", "Ἀνουβίωνος δραχμαὶ η", "cur12"), E("MONEY_AMOUNT", "η", "δραχμαὶ η\n", "m12"),
    E("PERSON", "Πτολεμαὶς Πτολεμαίου τοῦ Πτολεμαίου"),
], "relations": [
    ("m1", "cur1", "HAS_CURRENCY"), ("m2", "cur2", "HAS_CURRENCY"),
    ("m3", "cur3", "HAS_CURRENCY"), ("m4", "cur4", "HAS_CURRENCY"),
    ("m5", "cur5", "HAS_CURRENCY"), ("m6", "cur6", "HAS_CURRENCY"),
    ("m7", "cur7", "HAS_CURRENCY"), ("m8", "cur8", "HAS_CURRENCY"),
    ("m9", "cur9", "HAS_CURRENCY"), ("m10", "cur10", "HAS_CURRENCY"),
    ("m11", "cur11", "HAS_CURRENCY"), ("m12", "cur12", "HAS_CURRENCY"),
]}

SPEC["16690"] = {"entities": [  # land lease
    E("TRANSACTION", "ἐμίσθωσαν", None, "t1"),
    E("PERSON", "Σαραπίων ὁ καὶ Ἀχιλλεὺς Ζωίλου", None, "lessor1"),
    E("PERSON", "Σαρούβων Σερήνου τοῦ\nκαὶ Πετρωνιανοῦ", None, "lessor2"),
    E("PLACE", "Ὀξυρύγχων πόλεως"),
    E("PERSON", "Ἕλληνι Φειβάστοῦ", None, "lessee"), E("PERSON", "Θαήσιως"),
    E("PLACE", "κώμης Παείμεως"),
    E("DATE_REF", "ἔτη δύο", "εἰς\nἔτη δύο"),
    E("DATE_REF", "ιγ ἔτους"),
    E("PLACE", "Παεῖμιν"),
    E("UNIT", "ἀρούρας", None, "u1"),
    E("QUANTITY", "δύας\nτέταρτον", "ἀρούρας δύας\nτέταρτον", "q1"),
    E("COMMODITY", "πυροῦ", "ἐκφορίου\nἀποτάκτου κατʼ ἔτος πυροῦ", "c1"),
    E("UNIT", "ἀρταβῶν", None, "u2"),
    E("QUANTITY", "δέκα τεσσάρων", "ἀρταβῶν\nδέκα τεσσάρων", "q2"),
    E("COMMODITY", "πυρὸν νέον καθαρὸν ἄδολον"),
    E("DATE_REF", "ἔτους ιγ", "μίσθωσις. ἔτους ιγ"),
    E("PERSON", "Λουκίου Σεπτιμίου\nΣεουήρου"),
    E("PERSON", "Μάρκου Αὐρηλίου\nἈντωνίνου"),
    E("PERSON", "Πουβλίου Σεπτιμίου Γέτα"),
    E("DATE_REF", "Φαῶφι κη"),
    E("PERSON", "Ἕλλην Φειβάστου"),
    E("COMMODITY", "γῆν", "τὴν γῆν"),
    E("DATE_REF", "ἔτη δύο", "εἰς τὰ ἔτη δύο"),
], "relations": [
    ("q1", "u1", "HAS_UNIT"),
    ("c1", "q2", "HAS_QUANTITY"), ("q2", "u2", "HAS_UNIT"),
    ("lessor1", "t1", "PARTY_OF"), ("lessor2", "t1", "PARTY_OF"),
    ("lessee", "t1", "PARTY_OF"),
]}

SPEC["17157"] = {"entities": [  # sale of a female donkey
    E("PERSON", "Αὐρήλιος Κάστωρ Πεουῆτος", None, "seller"), E("PERSON", "Θαισοῦτος"),
    E("PLACE", "κώμης\nΘαλλοῦ"),
    E("PLACE", "Ἑρμοπολίτου νομοῦ"),
    E("PERSON", "Αὐρηλίῳ Ἑρμῇ Ἀνουβᾶτος", None, "buyer"), E("PERSON", "Δημητροῦτος"),
    E("PLACE", "Ὀξυρυγχιτῶν πόλεως"),
    E("TRANSACTION", "πέπρακά", None, "t1"),
    E("PLACE", "Ὀξυρυγχίτην"),
    E("COMMODITY", "ὄνον θήλειαν μυόχροον\nτελείαν", None, "c1"),
    E("PRICE_TERM", "τιμῆς"),
    E("CURRENCY", "ἀργυρίου σεβαστῶν νομίσματος"),
    E("CURRENCY", "τάλαντον", "νομίσματος τάλαντον ἓν", "cur1"),
    E("MONEY_AMOUNT", "ἓν", "τάλαντον ἓν γίνεται", "m1"),
    E("CURRENCY", "τάλαντον", "γίνεται τάλαντον α", "cur2"), E("MONEY_AMOUNT", "α", "τάλαντον α\n", "m2"),
    E("COMMODITY", "ὄνον", "τὴν δʼ αὐτὴν ὄνον"),
    E("DATE_REF", "ἔτους ζ"),
    E("PERSON", "Αὐτοκράτορος Καίσαρος Γαίου\nΑὐρηλίου Οὐαλερίου Διοκλητιανοῦ"),
    E("DATE_REF", "ἔτους ϛ", "καὶ ἔτους ϛ"),
    E("PERSON", "Μάρκου Αὐρηλίου\nΟὐαλερίου Μαξιμιανοῦ"),
    E("PERSON", "Αὐρήλιος Κάστωρ", "σεβαστῶν …\nΑὐρήλιος Κάστωρ"),
    E("COMMODITY", "ὄνον", "πέπρακα τὴν\nὄνον"),
    E("PRICE_TERM", "τιμῆς", "τὸ τῆς τιμῆς"),
    E("CURRENCY", "ἀργυρίου τάλαντον", "τιμῆς\nἀργυρίου τάλαντον", "cur3"),
    E("MONEY_AMOUNT", "ἓν", "τάλαντον ἓν πλήρης", "m3"),
], "relations": [
    ("m1", "cur1", "HAS_CURRENCY"), ("m2", "cur2", "HAS_CURRENCY"),
    ("m3", "cur3", "HAS_CURRENCY"),
    ("c1", "m1", "HAS_PRICE"),
    ("seller", "t1", "PARTY_OF"), ("buyer", "t1", "PARTY_OF"),
]}


def build(text: str, spec: dict, doc_id: str) -> tuple[list, list]:
    entities, keys, pos = [], {}, 0
    for label, surface, ctx, key in spec["entities"]:
        if ctx:
            # The context may begin before the previous span ends (a unit and
            # its numeral), so allow it to overlap backwards — but the surface
            # itself must still lie at or after `pos`.
            c = text.find(ctx, max(0, pos - len(ctx)))
            if c == -1:
                raise SystemExit(f"{doc_id}: context {ctx!r} not found near {pos}")
            start = text.find(surface, max(c, pos), c + len(ctx))
        else:
            start = text.find(surface, pos)
        if start == -1:
            raise SystemExit(f"{doc_id}: surface {surface!r} not found from {pos}")
        end = start + len(surface)
        if key:
            keys[key] = len(entities)
        entities.append({"start": start, "end": end, "label": label, "text": text[start:end]})
        pos = end
    relations = [
        {"head": keys[h], "tail": keys[t], "type": ty} for h, t, ty in spec["relations"]
    ]
    return entities, relations


def main() -> None:
    with Path("data/gold/to_annotate.jsonl").open(encoding="utf-8") as fh:
        batch = {json.loads(line)["doc_id"]: json.loads(line) for line in fh}
    out = []
    for doc_id, spec in SPEC.items():
        src = batch[doc_id]
        ents, rels = build(src["text"], spec, doc_id)
        out.append({
            "doc_id": doc_id,
            "text": src["text"],
            "meta": {**src["meta"], "annotator": "claude-opus-4-8", "provenance": "model_draft"},
            "entities": ents,
            "relations": rels,
            "double_annotate": src["double_annotate"],
        })
    path = Path("data/gold/annotated.jsonl")
    path.write_text("\n".join(json.dumps(d, ensure_ascii=False) for d in out) + "\n",
                    encoding="utf-8")
    print(f"wrote {len(out)} documents, "
          f"{sum(len(d['entities']) for d in out)} entities, "
          f"{sum(len(d['relations']) for d in out)} relations -> {path}")


if __name__ == "__main__":
    main()
